language: python
python:
          - '3.5'

dist: bionic
os: linux

# safelist
branches:
    only:
     - production

before_install:
        - pip install -r travis_requirements.txt

services:
          - postgresql

env: DJANGO_SETTINGS_MODULE=pur_beurre_project.settings.travis

script:
          - ./manage.py test
