language: python
python:
          - '3.5'

# safelist
branches:
    only:
     - production

before_script:
          - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="pur_beurre__project.settings"

services:
          - postgresql

env: DJANGO_SETTINGS_MODULE=pur_beurre_project.settings.travis

script:
          - ./manage.py test
